vich_uploader:
    db_driver: orm

    mappings:
        vehicule_image:
            uri_prefix: /images/vehicules
            upload_destination: '%kernel.project_dir%/public/media/img/vehicules'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true