vich_uploader:
    db_driver: orm

    mappings:
        vehicule_image:
            uri_prefix: media/img/Cars
            upload_destination: '%kernel.project_dir%/public/media/img/Cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        type_image:
            uri_prefix: media/img/types
            upload_destination: '%kernel.project_dir%/public/media/img/types'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true